### ISSUE TITLE
Missing description what the package does

### ISSUE THREAD

**Issue by nilswindisch** [siteleaf/siteleaf-atom#1]
and what's the benefit of installing/using it.

**Comment by sskylar** [comment]
The package is currently in development. At the moment it will allow you to preview Siteleaf sites inside of Atom:

![screenshot 2014-06-09 10 55 22](https://cloud.githubusercontent.com/assets/423740/3218063/30cbc73a-efe6-11e3-930b-4b0ab1a35b71.png)

Currently requires you to authenticate and config the site using the Siteleaf Ruby Gem, but this dependency will be removed.

The package is open source, so feel free to contribute your ideas.

**Comment by nilswindisch** [comment]
thank you!
